# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# q3equfz4igv6fajlod2lphysuklcj2erkznyousr7xjndgyc6yza
trigger:
  - main

variables:
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  - stage: Validate
    displayName: Release Stage
    jobs:
      - deployment: ValidateJob
        pool:
          vmImage: $(vmImage)
        variables:
          - template: variables/var-release.yml
        environment: UT
        strategy:
          runOnce:
            deploy:
              steps:
                - template: jobs/validate.yml
