# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# q3equfz4igv6fajlod2lphysuklcj2erkznyousr7xjndgyc6yza
trigger:
  - main

variables:
  - name: vmImage
    value: 'ubuntu-latest'
pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: Microsoft Azure Sponsorship 2021 (5f64f1ab-42b5-4fee-93ca-918ef6018d0c)
      KeyVaultName: 'kv-iot-devops-evaluate'
      SecretsFilter: '*'
      RunAsPreJob: false
  - powershell: |
      echo '$(artifacts-pw)'
      $destinationFolder = $HOME+"\.sbt"
      if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
      New-Item $HOME/.sbt/.credentials -ItemType file
      Add-Content  $HOME/.sbt/.credentials "`nrealm="
      Add-Content  $HOME/.sbt/.credentials "`nhost=bizonedev.pkgs.visualstudio.com"
      Add-Content  $HOME/.sbt/.credentials "`nuser=BizOneDev"
      Add-Content  $HOME/.sbt/.credentials "`npassword=$(artifacts-pw)"
  - script: sbt clean
    displayName: 'Running $ sbt clean'
  - script: sbt transformation/assembly transformation/publish
    displayName: 'Run $ sbt tran transformation/assembly transformation/publish'
