# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
  - checkout: self
    persistCredentials: true
  - script: sbt clean
    displayName: 'Running $ sbt clean'
  - script: sbt coverage test coverageReport coverageOff
    displayName: 'Running framework-test $ sbt coverage test coverageReport coverageOff'