# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
  - checkout: self
    persistCredentials: true
  - script: sbt clean
    displayName: 'Running $ sbt clean'
  - script: sbt coverage test coverageReport coverageOff
    displayName: 'Running framework-test $ sbt coverage test coverageReport coverageOff'
  - task: Bash@3
    displayName: 'set release/sit'
    inputs:
      targetType: 'inline'
      script: |
        git config --global user.email "$(user.email)"
        git config --global user.name "$(user.name)"
        git checkout -b release/uat origin/release/uat
        git merge origin/release/uat
        git push origin release/uat